HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:hc138
Implementation;Synthesis||null||@N: Running in 64-bit mode||hc138.srr(11);liberoaction://cross_probe/hdl/file/'C:\EDA\cpu74hc138\synthesis\hc138.srr'/linenumber/11||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||hc138.srr(15);liberoaction://cross_probe/hdl/file/'C:\EDA\cpu74hc138\synthesis\hc138.srr'/linenumber/15||null;null
Implementation;Synthesis|| CG364 ||@N: Synthesizing module hc138 in library work.||hc138.srr(26);liberoaction://cross_probe/hdl/file/'C:\EDA\cpu74hc138\synthesis\hc138.srr'/linenumber/26||hc138.v(21);liberoaction://cross_probe/hdl/file/'C:\EDA\cpu74hc138\hdl\hc138.v'/linenumber/21
Implementation;Synthesis||null||@N: Running in 64-bit mode||hc138.srr(38);liberoaction://cross_probe/hdl/file/'C:\EDA\cpu74hc138\synthesis\hc138.srr'/linenumber/38||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||hc138.srr(59);liberoaction://cross_probe/hdl/file/'C:\EDA\cpu74hc138\synthesis\hc138.srr'/linenumber/59||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||hc138.srr(82);liberoaction://cross_probe/hdl/file/'C:\EDA\cpu74hc138\synthesis\hc138.srr'/linenumber/82||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||hc138.srr(83);liberoaction://cross_probe/hdl/file/'C:\EDA\cpu74hc138\synthesis\hc138.srr'/linenumber/83||null;null
Implementation;Synthesis|| BN225 ||@N: Writing default property annotation file C:\EDA\cpu74hc138\synthesis\hc138.sap.||hc138.srr(104);liberoaction://cross_probe/hdl/file/'C:\EDA\cpu74hc138\synthesis\hc138.srr'/linenumber/104||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||hc138.srr(131);liberoaction://cross_probe/hdl/file/'C:\EDA\cpu74hc138\synthesis\hc138.srr'/linenumber/131||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||hc138.srr(132);liberoaction://cross_probe/hdl/file/'C:\EDA\cpu74hc138\synthesis\hc138.srr'/linenumber/132||null;null
Implementation;Synthesis|| MT320 ||@N: This timing report is an estimate of place and route data. For final timing results, use the FPGA vendor place and route report.||hc138.srr(237);liberoaction://cross_probe/hdl/file/'C:\EDA\cpu74hc138\synthesis\hc138.srr'/linenumber/237||null;null
Implementation;Synthesis|| MT322 ||@N: Clock constraints include only register-to-register paths associated with each individual clock.||hc138.srr(239);liberoaction://cross_probe/hdl/file/'C:\EDA\cpu74hc138\synthesis\hc138.srr'/linenumber/239||null;null
Implementation;Compile;RootName:hc138
Implementation;Compile||(null)||Please refer to the log file for details||hc138_compile_log.rpt;liberoaction://open_report/file/hc138_compile_log.rpt||(null);(null)
