HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:hc00
Implementation;Synthesis||null||@N: Running in 64-bit mode||hc00.srr(11);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc00\cpu74hc00\synthesis\hc00.srr'/linenumber/11||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||hc00.srr(15);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc00\cpu74hc00\synthesis\hc00.srr'/linenumber/15||null;null
Implementation;Synthesis|| CG364 ||@N: Synthesizing module hc00 in library work.||hc00.srr(29);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc00\cpu74hc00\synthesis\hc00.srr'/linenumber/29||hc00.v(21);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc00\cpu74hc00\hdl\hc00.v'/linenumber/21
Implementation;Synthesis||null||@N: Running in 64-bit mode||hc00.srr(41);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc00\cpu74hc00\synthesis\hc00.srr'/linenumber/41||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||hc00.srr(62);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc00\cpu74hc00\synthesis\hc00.srr'/linenumber/62||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||hc00.srr(84);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc00\cpu74hc00\synthesis\hc00.srr'/linenumber/84||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||hc00.srr(85);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc00\cpu74hc00\synthesis\hc00.srr'/linenumber/85||null;null
Implementation;Synthesis|| BN225 ||@N: Writing default property annotation file C:\EDA\74hc00\cpu74hc00\synthesis\hc00.sap.||hc00.srr(106);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc00\cpu74hc00\synthesis\hc00.srr'/linenumber/106||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||hc00.srr(131);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc00\cpu74hc00\synthesis\hc00.srr'/linenumber/131||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||hc00.srr(132);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc00\cpu74hc00\synthesis\hc00.srr'/linenumber/132||null;null
Implementation;Synthesis|| MT320 ||@N: This timing report is an estimate of place and route data. For final timing results, use the FPGA vendor place and route report.||hc00.srr(237);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc00\cpu74hc00\synthesis\hc00.srr'/linenumber/237||null;null
Implementation;Synthesis|| MT322 ||@N: Clock constraints include only register-to-register paths associated with each individual clock.||hc00.srr(239);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc00\cpu74hc00\synthesis\hc00.srr'/linenumber/239||null;null
Implementation;Compile;RootName:hc00
Implementation;Compile||(null)||Please refer to the log file for details about 1 Info(s)||hc00_compile_log.rpt;liberoaction://open_report/file/hc00_compile_log.rpt||(null);(null)
Implementation;Place and Route;RootName:hc00
Implementation;Place and Route||(null)||Please refer to the log file for details about 1 Info(s)||hc00_placeroute_log.rpt;liberoaction://open_report/file/hc00_placeroute_log.rpt||(null);(null)
