HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:hc02
Implementation;Synthesis||null||@N: Running in 64-bit mode||hc02.srr(11);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/11||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||hc02.srr(15);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/15||null;null
Implementation;Synthesis|| CG364 ||@N: Synthesizing module hc02 in library work.||hc02.srr(29);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/29||hc02.v(21);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\hdl\hc02.v'/linenumber/21
Implementation;Synthesis||null||@N: Running in 64-bit mode||hc02.srr(41);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/41||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||hc02.srr(62);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/62||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||hc02.srr(84);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/84||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||hc02.srr(85);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/85||null;null
Implementation;Synthesis|| BN225 ||@N: Writing default property annotation file C:\EDA\74hc02\cpu74hc02\synthesis\hc02.sap.||hc02.srr(113);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/113||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||hc02.srr(138);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/138||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||hc02.srr(139);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/139||null;null
Implementation;Synthesis||null||@N: Writing EDF file: C:\EDA\74hc02\cpu74hc02\synthesis\hc02.edn||hc02.srr(231);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/231||null;null
Implementation;Synthesis|| BW103 ||@N: The default time unit for the Synopsys Constraint File (SDC or FDC) is 1ns.||hc02.srr(232);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/232||null;null
Implementation;Synthesis|| BW107 ||@N: Synopsys Constraint File capacitance units using default value of 1pF ||hc02.srr(233);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/233||null;null
Implementation;Synthesis|| MT320 ||@N: This timing report is an estimate of place and route data. For final timing results, use the FPGA vendor place and route report.||hc02.srr(253);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/253||null;null
Implementation;Synthesis|| MT322 ||@N: Clock constraints include only register-to-register paths associated with each individual clock.||hc02.srr(255);liberoaction://cross_probe/hdl/file/'C:\EDA\74hc02\cpu74hc02\synthesis\hc02.srr'/linenumber/255||null;null
Implementation;Compile;RootName:hc02
Implementation;Compile||(null)||Please refer to the log file for details about 5 Info(s)||hc02_compile_log.log;liberoaction://open_report/file/hc02_compile_log.log||(null);(null)
Implementation;Place and Route;RootName:hc02
Implementation;Place and Route||(null)||Please refer to the log file for details about 2 Info(s)||hc02_layout_log.log;liberoaction://open_report/file/hc02_layout_log.log||(null);(null)
