HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:HC148
Implementation;Synthesis||null||@N: Running in 64-bit mode||HC148.srr(11);liberoaction://cross_probe/hdl/file/'D:\HC148\HC148\synthesis\HC148.srr'/linenumber/11||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||HC148.srr(15);liberoaction://cross_probe/hdl/file/'D:\HC148\HC148\synthesis\HC148.srr'/linenumber/15||null;null
Implementation;Synthesis|| CG364 ||@N: Synthesizing module HC148 in library work.||HC148.srr(26);liberoaction://cross_probe/hdl/file/'D:\HC148\HC148\synthesis\HC148.srr'/linenumber/26||HC148.v(3);liberoaction://cross_probe/hdl/file/'D:\HC148\HC148\hdl\HC148.v'/linenumber/3
Implementation;Synthesis||null||@N: Running in 64-bit mode||HC148.srr(38);liberoaction://cross_probe/hdl/file/'D:\HC148\HC148\synthesis\HC148.srr'/linenumber/38||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||HC148.srr(59);liberoaction://cross_probe/hdl/file/'D:\HC148\HC148\synthesis\HC148.srr'/linenumber/59||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||HC148.srr(82);liberoaction://cross_probe/hdl/file/'D:\HC148\HC148\synthesis\HC148.srr'/linenumber/82||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||HC148.srr(83);liberoaction://cross_probe/hdl/file/'D:\HC148\HC148\synthesis\HC148.srr'/linenumber/83||null;null
Implementation;Synthesis|| BN225 ||@N: Writing default property annotation file D:\HC148\HC148\synthesis\HC148.sap.||HC148.srr(104);liberoaction://cross_probe/hdl/file/'D:\HC148\HC148\synthesis\HC148.srr'/linenumber/104||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||HC148.srr(131);liberoaction://cross_probe/hdl/file/'D:\HC148\HC148\synthesis\HC148.srr'/linenumber/131||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||HC148.srr(132);liberoaction://cross_probe/hdl/file/'D:\HC148\HC148\synthesis\HC148.srr'/linenumber/132||null;null
Implementation;Synthesis|| MT320 ||@N: This timing report is an estimate of place and route data. For final timing results, use the FPGA vendor place and route report.||HC148.srr(237);liberoaction://cross_probe/hdl/file/'D:\HC148\HC148\synthesis\HC148.srr'/linenumber/237||null;null
Implementation;Synthesis|| MT322 ||@N: Clock constraints include only register-to-register paths associated with each individual clock.||HC148.srr(239);liberoaction://cross_probe/hdl/file/'D:\HC148\HC148\synthesis\HC148.srr'/linenumber/239||null;null
Implementation;Compile;RootName:HC148
Implementation;Compile||(null)||Please refer to the log file for details||HC148_compile_log.rpt;liberoaction://open_report/file/HC148_compile_log.rpt||(null);(null)
